# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)
Team.create!("name"=>"India", "won"=>7, "drawn"=>1, "lost"=>1, "noresult"=>0)
Team.create!("name"=>"Australia", "won"=>7, "drawn"=>0, "lost"=>2, "noresult"=>0)
Team.create!("name"=>"England", "won"=>6, "drawn"=>0, "lost"=>3, "noresult"=>0)
Team.create!("name"=>"New Zealand", "won"=>5, "drawn"=>0, "lost"=>3, "noresult"=>1)
Player.create!("name"=>"Jason Roy", DOB:"1990-07-21", "team_id"=>3, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"RM", "domesticteam"=>"Surrey")
Player.create!("name"=>"Jonny Bairstow", DOB:"1989-09-26", "team_id"=>3, "role"=>"WicketKeeper", "battinghand"=>"Right", "bowlingstyle"=>"NA", "domesticteam"=>"Yorkshire")
Player.create!("name"=>"Joe Root", DOB:"1990-12-30", "team_id"=>3, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Yorkshire")
Player.create!("name"=>"Jofra Archer", DOB:"1995-04-01", "team_id"=>3, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Sussex")
Player.create!("name"=>"Eoin Morgan", DOB:"1986-09-10", "team_id"=>3, "role"=>"Batter", "battinghand"=>"Left", "bowlingstyle"=>"RM", "domesticteam"=>"Middlesex")
Player.create!("name"=>"Ben Stokes", DOB:"1991-04-04", "team_id"=>3, "role"=>"AllRounder", "battinghand"=>"Left", "bowlingstyle"=>"RFM", "domesticteam"=>"Durham")
Player.create!("name"=>"Jos Buttler", DOB:"1990-09-08", "team_id"=>3, "role"=>"WicketKeeper", "battinghand"=>"Right", "bowlingstyle"=>"NA", "domesticteam"=>"Lancashire")
Player.create!("name"=>"Chris Woakes", DOB:"1989-03-02", "team_id"=>3, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"RFM", "domesticteam"=>"Warwickshire")
Player.create!("name"=>"Liam Plunkett", DOB:"1985-04-06", "team_id"=>3, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Surrey")
Player.create!("name"=>"Adil Rashid", DOB:"1988-02-17", "team_id"=>3, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"LB", "domesticteam"=>"Yorkshire")
Player.create!("name"=>"Mark Wood", DOB:"1990-01-11", "team_id"=>3, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Durham")
Player.create!("name"=>"Martin Guptill", DOB:"1986-09-30", "team_id"=>4, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Worcestershire")
Player.create!("name"=>"Henry Nicholls", DOB:"1991-11-15", "team_id"=>4, "role"=>"Batter", "battinghand"=>"Left", "bowlingstyle"=>"OB", "domesticteam"=>"Canterbury")
Player.create!("name"=>"Kane Williamson", DOB:"1990-08-08", "team_id"=>4, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Sunrisers Hyderabad")
Player.create!("name"=>"Ross Taylor", DOB:"1984-03-08", "team_id"=>4, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Middlesex")
Player.create!("name"=>"Thomas Latham", DOB:"1992-04-02", "team_id"=>4, "role"=>"Batter", "battinghand"=>"Left", "bowlingstyle"=>"RM", "domesticteam"=>"Canterbury")
Player.create!("name"=>"James Neesham", DOB:"1990-09-17", "team_id"=>4, "role"=>"AllRounder", "battinghand"=>"Left", "bowlingstyle"=>"RM", "domesticteam"=>"Wellington")
Player.create!("name"=>"Colin de Grandhomme", DOB:"1986-07-22", "team_id"=>4, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"RFM", "domesticteam"=>"Royal Challengers Bangalore")
Player.create!("name"=>"Mitchell Santner", DOB:"1992-02-05", "team_id"=>4, "role"=>"AllRounder", "battinghand"=>"Left", "bowlingstyle"=>"SLA", "domesticteam"=>"Chennai Super Kings")
Player.create!("name"=>"Matthew Henry", DOB:"1991-12-14", "team_id"=>4, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RFM", "domesticteam"=>"Canterbury")
Player.create!("name"=>"Trent Boult", DOB:"1989-07-22", "team_id"=>4, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"LFM", "domesticteam"=>"Mumbai Indians")
Player.create!("name"=>"Lockie Ferguson", DOB:"1991-07-13", "team_id"=>4, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Auckland")
Player.create!("name"=>"James Vince", DOB:"1991-03-14", "team_id"=>3, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"RM", "domesticteam"=>"Hampshire")
Player.create!("name"=>"Aaron Finch", DOB:"1986-11-17", "team_id"=>2, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"SLA", "domesticteam"=>"Surrey")
Player.create!("name"=>"David Warner", DOB:"1986-08-27", "team_id"=>2, "role"=>"Batter", "battinghand"=>"Left", "bowlingstyle"=>"LB", "domesticteam"=>"Sunrisers Hyderabad")
Player.create!("name"=>"Usman Khawaja", DOB:"1986-12-18", "team_id"=>2, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Queensland")
Player.create!("name"=>"Steve Smith", DOB:"1989-06-02", "team_id"=>2, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"LB", "domesticteam"=>"New South Wales")
Player.create!("name"=>"Glenn Maxwell", DOB:"1988-10-14", "team_id"=>2, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Victoria")
Player.create!("name"=>"Marcus Stoinis", DOB:"1989-08-16", "team_id"=>2, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"RM", "domesticteam"=>"Western Australia")
Player.create!("name"=>"Alex Carey", DOB:"1991-08-27", "team_id"=>2, "role"=>"WicketKeeper", "battinghand"=>"Left", "bowlingstyle"=>"NA", "domesticteam"=>"Sussex")
Player.create!("name"=>"Pat Cummins", DOB:"1993-05-08", "team_id"=>2, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Sydney Thunder")
Player.create!("name"=>"Mitchell Starc", DOB:"1990-01-30", "team_id"=>2, "role"=>"Bowler", "battinghand"=>"Left", "bowlingstyle"=>"LF", "domesticteam"=>"New South Wales")
Player.create!("name"=>"Moeen Ali", DOB:"1987-06-18", "team_id"=>3, "role"=>"AllRounder", "battinghand"=>"Left", "bowlingstyle"=>"OB", "domesticteam"=>"Worcestershire")
Player.create!("name"=>"Nathan Lyon", DOB:"1987-11-20", "team_id"=>2, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"New South Wales")
Player.create!("name"=>"Jason Behrendorff", DOB:"1990-04-20", "team_id"=>2, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"LFM", "domesticteam"=>"Western Australia")
Player.create!("name"=>"Ish Sodhi", DOB:"1992-10-31", "team_id"=>4, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"LB", "domesticteam"=>"Northern Districts")
Player.create!("name"=>"Kannur Rahul", DOB:"1992-04-18", "team_id"=>1, "role"=>"WicketKeeper", "battinghand"=>"Right", "bowlingstyle"=>"NA", "domesticteam"=>"Kings XI Punjab")
Player.create!("name"=>"Rohit Sharma", DOB:"1987-04-30", "team_id"=>1, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Mumbai Indians")
Player.create!("name"=>"Virat Kohli", DOB:"1988-11-05", "team_id"=>1, "role"=>"Batter", "battinghand"=>"Right", "bowlingstyle"=>"RM", "domesticteam"=>"Royal Challengers Bangalore")
Player.create!("name"=>"Rishabh Pant", DOB:"1997-10-04", "team_id"=>1, "role"=>"WicketKeeper", "battinghand"=>"Left", "bowlingstyle"=>"NA", "domesticteam"=>"Delhi")
Player.create!("name"=>"Hardik Pandya", DOB:"1993-10-11", "team_id"=>1, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"RFM", "domesticteam"=>"Mumbai Indians")
Player.create!("name"=>"MS Dhoni", DOB:"1981-07-07", "team_id"=>1, "role"=>"WicketKeeper", "battinghand"=>"Right", "bowlingstyle"=>"NA", "domesticteam"=>"Chennai Super Kings")
Player.create!("name"=>"Kedar Jadhav", DOB:"1985-03-26", "team_id"=>1, "role"=>"AllRounder", "battinghand"=>"Right", "bowlingstyle"=>"OB", "domesticteam"=>"Chennai Super Kings")
Player.create!("name"=>"Kuldeep Yadav", DOB:"1994-12-14", "team_id"=>1, "role"=>"Bowler", "battinghand"=>"Left", "bowlingstyle"=>"SLA", "domesticteam"=>"Kolkata Knight Riders")
Player.create!("name"=>"Mohammed Shami", DOB:"1990-09-03", "team_id"=>1, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Kings XI Punjab")
Player.create!("name"=>"Yuzvendra Chahal", DOB:"1990-07-23", "team_id"=>1, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"LB", "domesticteam"=>"Royal Challengers Bangalore")
Player.create!("name"=>"Jasprit Bumrah", DOB:"1993-12-06", "team_id"=>1, "role"=>"Bowler", "battinghand"=>"Right", "bowlingstyle"=>"RF", "domesticteam"=>"Mumbai Indians")





Match.create!(date:"2019-06-30", "hometeam_id"=>3, "awayteam_id"=>1, "stadium"=>"Edgbaston")
Innings.create!("match_id"=>1, hometeambatted:1, "byes"=>2, "legbyes"=>2, "penalties"=>0)
Innings.create!("match_id"=>1, hometeambatted:0, "byes"=>0, "legbyes"=>1, "penalties"=>0)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>1, "runs"=>66, "balls"=>57, "fours"=>7, "sixes"=>2, "howout"=>"Caught", "bowler_id"=>43, "fielder_id"=>43, "batsman_number"=>1)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>2, "runs"=>111, "balls"=>109, "fours"=>10, "sixes"=>6, "howout"=>"Caught", "bowler_id"=>44, "fielder_id"=>39, "batsman_number"=>2)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>3, "runs"=>44, "balls"=>54, "fours"=>2, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>44, "fielder_id"=>30, "batsman_number"=>3)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>5, "runs"=>1, "balls"=>9, "fours"=>0, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>44, "fielder_id"=>42, "batsman_number"=>4)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>6, "runs"=>79, "balls"=>54, "fours"=>6, "sixes"=>3, "howout"=>"Caught", "bowler_id"=>46, "fielder_id"=>46, "batsman_number"=>5)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>7, "runs"=>20, "balls"=>8, "fours"=>1, "sixes"=>2, "howout"=>"Caught", "bowler_id"=>44, "fielder_id"=>44, "batsman_number"=>6)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>8, "runs"=>7, "balls"=>5, "fours"=>1, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>44, "fielder_id"=>37, "batsman_number"=>7)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>9, "runs"=>1, "balls"=>4, "fours"=>0, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>8)
BattingInnings.create!("Innings_id"=>1, "Player_id"=>4, "runs"=>0, "balls"=>0, "fours"=>0, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>9)

BattingInnings.create!("Innings_id"=>2, "Player_id"=>36, "runs"=>0, "balls"=>9, "fours"=>0, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>8, "fielder_id"=>8, "batsman_number"=>1)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>37, "runs"=>102, "balls"=>109, "fours"=>15, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>8, "fielder_id"=>7, "batsman_number"=>2)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>38, "runs"=>66, "balls"=>76, "fours"=>7, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>9, "fielder_id"=>9, "batsman_number"=>3)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>39, "runs"=>32, "balls"=>29, "fours"=>4, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>9, "fielder_id"=>8, "batsman_number"=>4)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>40, "runs"=>45, "balls"=>33, "fours"=>4, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>9, "fielder_id"=>9, "batsman_number"=>5)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>41, "runs"=>42, "balls"=>31, "fours"=>4, "sixes"=>1, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>6)
BattingInnings.create!("Innings_id"=>2, "Player_id"=>42, "runs"=>12, "balls"=>13, "fours"=>1, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>7)

BowlingInnings.create!("Innings_id"=>1, "Player_id"=>44, "overs"=>10.0, "maidens"=>1, "runs"=>69, "wickets"=>5, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>1, "Player_id"=>46, "overs"=>10.0, "maidens"=>1, "runs"=>44, "wickets"=>1, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>1, "Player_id"=>45, "overs"=>10.0, "maidens"=>0, "runs"=>88, "wickets"=>0, "no_balls"=>0, "wides"=>2)
BowlingInnings.create!("Innings_id"=>1, "Player_id"=>40, "overs"=>10.0, "maidens"=>0, "runs"=>60, "wickets"=>0, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>1, "Player_id"=>43, "overs"=>10.0, "maidens"=>0, "runs"=>72, "wickets"=>1, "no_balls"=>0, "wides"=>0)

BowlingInnings.create!("Innings_id"=>2, "Player_id"=>8, "overs"=>10.0, "maidens"=>3, "runs"=>58, "wickets"=>2, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>2, "Player_id"=>4, "overs"=>10.0, "maidens"=>0, "runs"=>45, "wickets"=>0, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>2, "Player_id"=>9, "overs"=>10.0, "maidens"=>0, "runs"=>55, "wickets"=>3, "no_balls"=>0, "wides"=>4)
BowlingInnings.create!("Innings_id"=>2, "Player_id"=>11, "overs"=>10.0, "maidens"=>0, "runs"=>73, "wickets"=>0, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>2, "Player_id"=>10, "overs"=>6.0, "maidens"=>0, "runs"=>40, "wickets"=>0, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>2, "Player_id"=>6, "overs"=>4.0, "maidens"=>0, "runs"=>34, "wickets"=>0, "no_balls"=>0, "wides"=>0)





Match.create!(date:"2019-06-25", "hometeam_id"=>3, "awayteam_id"=>2, "stadium"=>"Lord's")
Innings.create!("match_id"=>2, hometeambatted:1, "byes"=>1, "legbyes"=>5, "penalties"=>0)
Innings.create!("match_id"=>2, hometeambatted:0, "byes"=>0, "legbyes"=>4, "penalties"=>0)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>23, "runs"=>0, "balls"=>2, "fours"=>0, "sixes"=>0, "howout"=>"Bowled", "bowler_id"=>35, "fielder_id"=>nil, "batsman_number"=>1)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>2, "runs"=>27, "balls"=>39, "fours"=>5, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>35, "fielder_id"=>31, "batsman_number"=>2)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>3, "runs"=>8, "balls"=>9, "fours"=>2, "sixes"=>0, "howout"=>"LBW", "bowler_id"=>32, "fielder_id"=>nil, "batsman_number"=>3)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>5, "runs"=>4, "balls"=>7, "fours"=>1, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>32, "fielder_id"=>31, "batsman_number"=>4)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>6, "runs"=>89, "balls"=>115, "fours"=>8, "sixes"=>2, "howout"=>"Bowled", "bowler_id"=>32, "fielder_id"=>nil, "batsman_number"=>5)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>7, "runs"=>25, "balls"=>27, "fours"=>2, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>29, "fielder_id"=>26, "batsman_number"=>6)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>8, "runs"=>26, "balls"=>34, "fours"=>2, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>35, "fielder_id"=>24, "batsman_number"=>7)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>33, "runs"=>6, "balls"=>9, "fours"=>1, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>35, "fielder_id"=>30, "batsman_number"=>8)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>9, "runs"=>25, "balls"=>20, "fours"=>3, "sixes"=>1, "howout"=>"Caught", "bowler_id"=>32, "fielder_id"=>29, "batsman_number"=>9)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>4, "runs"=>1, "balls"=>4, "fours"=>0, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>35, "fielder_id"=>25, "batsman_number"=>10)
BattingInnings.create!("Innings_id"=>3, "Player_id"=>10, "runs"=>1, "balls"=>2, "fours"=>0, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>11)

BattingInnings.create!("Innings_id"=>4, "Player_id"=>24, "runs"=>100, "balls"=>116, "fours"=>11, "sixes"=>2, "howout"=>"Caught", "bowler_id"=>4, "fielder_id"=>8, "batsman_number"=>1)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>25, "runs"=>53, "balls"=>61, "fours"=>6, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>33, "fielder_id"=>3, "batsman_number"=>2)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>26, "runs"=>23, "balls"=>29, "fours"=>1, "sixes"=>0, "howout"=>"Bowled", "bowler_id"=>6, "fielder_id"=>nil, "batsman_number"=>3)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>27, "runs"=>38, "balls"=>34, "fours"=>5, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>8, "fielder_id"=>4, "batsman_number"=>4)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>28, "runs"=>12, "balls"=>8, "fours"=>1, "sixes"=>1, "howout"=>"Caught", "bowler_id"=>11, "fielder_id"=>7, "batsman_number"=>5)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>29, "runs"=>8, "balls"=>15, "fours"=>1, "sixes"=>0, "howout"=>"RunOut", "bowler_id"=>nil, "fielder_id"=>7, "batsman_number"=>6)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>30, "runs"=>38, "balls"=>27, "fours"=>5, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>7)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>31, "runs"=>1, "balls"=>4, "fours"=>0, "sixes"=>0, "howout"=>"Caught", "bowler_id"=>8, "fielder_id"=>7, "batsman_number"=>8)
BattingInnings.create!("Innings_id"=>4, "Player_id"=>32, "runs"=>4, "balls"=>6, "fours"=>0, "sixes"=>0, "howout"=>"NotOut", "bowler_id"=>nil, "fielder_id"=>nil, "batsman_number"=>9)

BowlingInnings.create!("Innings_id"=>3, "Player_id"=>35, "overs"=>10.0, "maidens"=>0, "runs"=>44, "wickets"=>5, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>3, "Player_id"=>32, "overs"=>8.4, "maidens"=>1, "runs"=>43, "wickets"=>4, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>3, "Player_id"=>31, "overs"=>8.0, "maidens"=>0, "runs"=>41, "wickets"=>0, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>3, "Player_id"=>34, "overs"=>9.0, "maidens"=>0, "runs"=>43, "wickets"=>0, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>3, "Player_id"=>29, "overs"=>7.0, "maidens"=>0, "runs"=>29, "wickets"=>1, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>3, "Player_id"=>28, "overs"=>2.0, "maidens"=>0, "runs"=>15, "wickets"=>0, "no_balls"=>0, "wides"=>0)

BowlingInnings.create!("Innings_id"=>4, "Player_id"=>8, "overs"=>10.0, "maidens"=>0, "runs"=>46, "wickets"=>2, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>4, "Player_id"=>4, "overs"=>9.0, "maidens"=>0, "runs"=>56, "wickets"=>1, "no_balls"=>0, "wides"=>1)
BowlingInnings.create!("Innings_id"=>4, "Player_id"=>11, "overs"=>9.0, "maidens"=>0, "runs"=>59, "wickets"=>1, "no_balls"=>0, "wides"=>2)
BowlingInnings.create!("Innings_id"=>4, "Player_id"=>6, "overs"=>6.0, "maidens"=>0, "runs"=>29, "wickets"=>1, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>4, "Player_id"=>33, "overs"=>6.0, "maidens"=>0, "runs"=>42, "wickets"=>1, "no_balls"=>0, "wides"=>0)
BowlingInnings.create!("Innings_id"=>4, "Player_id"=>10, "overs"=>10.0, "maidens"=>0, "runs"=>49, "wickets"=>0, "no_balls"=>0, "wides"=>0)
